import { withLazySyntaxStyle } from "./syntax";
import type { AppTheme } from "./types";

/** Light theme based on Zed's built-in One Light palette. */
export const ONE_LIGHT_THEME: AppTheme = withLazySyntaxStyle(
  {
    id: "one-light",
    label: "One Light",
    appearance: "light",
    background: "#dcdcdd",
    panel: "#f7f7f8",
    panelAlt: "#ebebec",
    border: "#c9c9ca",
    accent: "#5c78e2",
    accentMuted: "#cbcdf6",
    text: "#242529",
    muted: "#58585a",
    addedBg: "#e6f3e5",
    removedBg: "#fae6e3",
    contextBg: "#f7f7f8",
    addedContentBg: "#cfe8cd",
    removedContentBg: "#f2c9c3",
    contextContentBg: "#f7f7f8",
    addedSignColor: "#50a14f",
    removedSignColor: "#e45649",
    lineNumberBg: "#f7f7f8",
    lineNumberFg: "#8d9099",
    selectedHunk: "#cbcdf6",
    badgeAdded: "#50a14f",
    badgeRemoved: "#e45649",
    badgeNeutral: "#a48819",
    fileNew: "#669f59",
    fileDeleted: "#d36151",
    fileRenamed: "#5c78e2",
    fileModified: "#a48819",
    fileUntracked: "#3882b7",
    noteBorder: "#5c78e2",
    noteBackground: "#eceeff",
    noteTitleBackground: "#dfe2ff",
    noteTitleText: "#5c78e2",
  },
  {
    default: "#242529",
    keyword: "#8f3f95",
    string: "#4f8f45",
    comment: "#a2a3a7",
    number: "#ad6e25",
    function: "#5b79e3",
    property: "#d3604f",
    type: "#3882b7",
    punctuation: "#4d4f52",
  },
);
